# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20190615_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_messsage',
            field=models.CharField(max_length=100),
        ),
    ]
