# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messsage',
            new_name='user_messsage',
        ),
    ]
