# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('got_app', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event', to='got_app.User'),
        ),
    ]
