# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srshows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='Description description description'),
            preserve_default=False,
        ),
    ]
