# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-13 03:05
from __future__ import unicode_literals

import apps.srshows_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srshows_app', '0002_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(validators=[apps.srshows_app.models.no_future]),
        ),
    ]
